### ISSUE TITLE
File Explorer does not list datasets when the search string contains a #

### ISSUE THREAD

**Issue by FreekCornelis** [zowe/zlux-file-explorer#41] opened 2019-09-30 14:58 UTC
Searching for `SYMME.JES#*` nor `SYMME.JES#*.**` displays any datasets:

![image](https://user-images.githubusercontent.com/55885539/65890369-0e43a780-e3a3-11e9-9cd7-990f53d38d30.png)

![image](https://user-images.githubusercontent.com/55885539/65890479-3c28ec00-e3a3-11e9-8247-339ab8da69c2.png)

where as `SYMME.JES*.**` does:
![image](https://user-images.githubusercontent.com/55885539/65890543-54990680-e3a3-11e9-9bf7-65dec6bf9481.png)

**Comment by DivergentEuropeans** [comment] 2019-09-30 17:47
Hey @FreekCornelis 
This looks like a duplicate of https://github.com/zowe/zlux-file-explorer/issues/40
So I am going to ahead and close this one. Let me know if this is wrong,
Thanks

**Closed by DivergentEuropeans** 2019-09-30 17:47 UTC

**Comment by FreekCornelis** [comment] 2019-10-01 09:06
Hi @DivergentEuropeans , IHMO #40 en #41 are different. They are probably related, but fixing one of them might not have fixed the other if there is no single root cause and place where it can be fixed.
Hence, I would like #41 to be reopened, so that this specific case (searching for datasets that have a # in the name) is checked as well, and will be fixed.
Thanks.
